### ISSUE TITLE
pytorch version for tamnun

### ISSUE THREAD

**Issue by Liranbz** [hiredscorelabs/tamnun-ml#11]
Hi,
Can I use tamnun lib. by using other versions of pytorch, and not only torch 1.1.0?
Best.

**Comment by shudima** [comment]
Hi,
Yes, there should be no issues.
You can either: install tamnun and then install your version of pytorch, or clone this repo, update the setup.py file with the version you want and then do `pip install .`

**Comment by Liranbz** [comment]
I change it:
```

name='tamnun',
    version=VERSION,
    description="An easy to use open-source library for advanced Deep Learning and Natural Language Processing",
    long_description=open("README.md", "r", encoding='utf-8').read(),
    long_description_content_type="text/markdown",
    url="https://github.com/hiredscorelabs/tamnun-ml",
    keywords='Deep Learning Natural Language Processing NLP Machine Learning Transfer Learning',
    license='Apache',
    packages=find_packages(exclude=['test*']),
    install_requires=[
        'numpy==1.15.4',
        'scikit-learn==0.20.2',
        'torch==1.0.0',
        'pytorch-transformers',
    ],
```

 but I got this error:
![image](https://user-images.githubusercontent.com/51919286/88551711-d5f51000-d02b-11ea-8229-25617bdf2667.png)

I have this torch version:
![image](https://user-images.githubusercontent.com/51919286/88551788-f2914800-d02b-11ea-9a17-6f2bec503e01.png)

Do you have any idea?
Thank you
