### ISSUE TITLE
Support for other pretrained BERT models

### ISSUE THREAD

**Issue by thoppe** [hiredscorelabs/tamnun-ml#4]
Thanks for the great module, it seems to work right out of the box! 

Is there a way to specify a different pretrained model other than those listed in [here](https://github.com/huggingface/pytorch-transformers/blob/98dc30b21e3df6528d0dd17f0910ffea12bc0f33/pytorch_pretrained_bert/modeling.py#L36)?

It would be great to use [bioBERT](https://github.com/dmis-lab/biobert) or [sciBERT](https://github.com/allenai/scibert), the latter of which has a better vocabulary. A quick look suggest that you're using `pytorch_transformers.BertTokenizer` which seems to have [methods](https://github.com/huggingface/pytorch-transformers/blob/master/pytorch_transformers/tokenization_bert.py#L111) for custom calls.

**Comment by shudima** [comment]
Regarding bioBERT, it seems like it's a `BertModel` object from HuggingFace with different configuration, if so, you can pass it as "initial_model" to "BertClassifier" like this: 
```python
biobert = BertModel() 
clf = BertClassifier(num_of_classes=num_of_classes, bert_initial_model=biobert)
```
Please make sure you're using the right vectorizer 


Regarding sciBERT,  it looks like it's an `nn.Module` sub-class, if this is the case, you can use the `TorchEstimator` class to train it, like this:

```python
clf = TorchEstimator(module=scibert)
```

 At the moment, you can customize the `Vectorizer` by:
```python
vectorizer = BertVectorizer()
vectorizer.tokenizer = YourTokenizerFromHuggingFace()
```

In the future we'll add support for injecting different tokenizers into the vectorizer.
Hope this answers your question.

**Comment by thoppe** [comment]
This is perfect, thank you! It might be worth linking this issue in the
documentation in case anyone else has the same question.
