### ISSUE TITLE
training on gpu, predicting on cpu

### ISSUE THREAD

**Issue by nitzgado** [hiredscorelabs/tamnun-ml#5]
Hi,
I tried predicting with the trained (pretrained+fine tuned)  model using a server on a docker container, but had a problem.
looks like the model can only predict in a GPU environment (and indeed I managed to upload a local server on my machine).
I tried both loading the model with pickle and loading the model using torch.load with map_device = 'cpu', but still it had an error whenever i tried to predict.

**Comment by shudima** [comment]
If you're loading with pickle, you should be able to do one of those:

model = pickle.load(model_file)

model.module.cpu()
or
model.module.to(device) 
When device is CPU.

**Comment by nitzgado** [comment]
got the following error:
AttributeError: 'BertClassifier' object has no attribute 'module'

**Comment by shudima** [comment]
Sorry, try model.model.to(device)
