### ISSUE TITLE
Training Bert on Hebrew dataset

### ISSUE THREAD

**Issue by orenpapers** [hiredscorelabs/tamnun-ml#6]
Is it possible to train BERT on Hebrew dataset? (For example Wiki dump)

**Comment by shudima** [comment]
Yes, but unfortunately not with this library. This library is used to fine tune already trained BERT.
You can try to use HuggingFace pytorch_transofmers library to train BERT from scratch.
There's a version of BERT that was trained on 108 languages including Hebrew. Maybe it will be good enough for you. You can see an example of Hebrew sentiment analysis using this version here:
https://github.com/shudima/notebooks/blob/master/hebrew_snetiment_analysis.ipynb
